export const ACTIVITY_LOG_REPOSITORY = Symbol('ACTIVITY_LOG_REPOSITORY');
export const ADMIN_DASHBOARD_REPOSITORY = Symbol('ADMIN_DASHBOARD_REPOSITORY');
export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const PRODUCT_VARIANT_REPOSITORY = Symbol('PRODUCT_VARIANT_REPOSITORY');
export const COUPON_REPOSITORY = Symbol('COUPON_REPOSITORY');
export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const ORDER_ITEM_REPOSITORY = Symbol('ORDER_ITEM_REPOSITORY');
export const POINT_TRANSACTION_REPOSITORY = Symbol(
  'POINT_TRANSACTION_REPOSITORY',
);
export const POINT_REWARD_REPOSITORY = Symbol('POINT_REWARD_REPOSITORY');
export const FAQ_REPOSITORY = Symbol('FAQ_REPOSITORY');
export const PAYMENT_METHOD_CONFIG_REPOSITORY = Symbol(
  'PAYMENT_METHOD_CONFIG_REPOSITORY',
);
export const BANNER_REPOSITORY = Symbol('BANNER_REPOSITORY');
