/** Injection tokens for repository interfaces */
export const REPOSITORY_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  PRODUCT_REPOSITORY: 'PRODUCT_REPOSITORY',
  PRODUCT_VARIANT_REPOSITORY: 'PRODUCT_VARIANT_REPOSITORY',
  CATEGORY_REPOSITORY: 'CATEGORY_REPOSITORY',
  ORDER_REPOSITORY: 'ORDER_REPOSITORY',
  ORDER_ITEM_REPOSITORY: 'ORDER_ITEM_REPOSITORY',
  COUPON_REPOSITORY: 'COUPON_REPOSITORY',
  ACTIVITY_LOG_REPOSITORY: 'ACTIVITY_LOG_REPOSITORY',
} as const;

/** BullMQ queue names */
export const QUEUE_NAMES = {
  ORDER_PROCESSING: 'order-processing',
  PAYMENT_WEBHOOK: 'payment-webhook',
  NOTIFICATION: 'notification',
  FILE_PROCESSING: 'file-processing',
} as const;

/** Activity log actions */
export const LOG_ACTIONS = {
  // Auth
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  REGISTER: 'REGISTER',
  LOGOUT: 'LOGOUT',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',

  // User
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_ACTIVATED: 'USER_ACTIVATED',

  // Product
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  PRODUCT_ACTIVATED: 'PRODUCT_ACTIVATED',
  PRODUCT_DEACTIVATED: 'PRODUCT_DEACTIVATED',
  VARIANT_CREATED: 'VARIANT_CREATED',
  VARIANT_UPDATED: 'VARIANT_UPDATED',
  VARIANT_DELETED: 'VARIANT_DELETED',

  // Order
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_PAID: 'ORDER_PAID',
  ORDER_PROCESSING: 'ORDER_PROCESSING',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_REFUNDED: 'ORDER_REFUNDED',

  // Payment
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_WEBHOOK_RECEIVED: 'PAYMENT_WEBHOOK_RECEIVED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  // Coupon
  COUPON_CREATED: 'COUPON_CREATED',
  COUPON_UPDATED: 'COUPON_UPDATED',
  COUPON_APPLIED: 'COUPON_APPLIED',
  COUPON_DEACTIVATED: 'COUPON_DEACTIVATED',

  // Delivery
  DELIVERY_NOTE_ADDED: 'DELIVERY_NOTE_ADDED',
  DELIVERY_COMPLETED: 'DELIVERY_COMPLETED',

  // System
  SYSTEM_STARTUP: 'SYSTEM_STARTUP',
  SYSTEM_SHUTDOWN: 'SYSTEM_SHUTDOWN',
} as const;
