import { forwardRef, Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { JwtModule, JwtSignOptions } from '@nestjs/jwt';
import {
  ACTIVITY_LOG_REPOSITORY,
  ADMIN_DASHBOARD_REPOSITORY,
  CATEGORY_REPOSITORY,
  COUPON_REPOSITORY,
  ORDER_ITEM_REPOSITORY,
  ORDER_REPOSITORY,
  PRODUCT_REPOSITORY,
  PRODUCT_VARIANT_REPOSITORY,
  USER_REPOSITORY,
  POINT_TRANSACTION_REPOSITORY,
  POINT_REWARD_REPOSITORY,
  FAQ_REPOSITORY,
  PAYMENT_METHOD_CONFIG_REPOSITORY,
} from '../domain/repositories/tokens';
import { InfrastructureModule } from '../infrastructure';
import {
  PrismaActivityLogRepository,
  PrismaAdminDashboardRepository,
  PrismaCategoryRepository,
  PrismaCouponRepository,
  PrismaOrderItemRepository,
  PrismaOrderRepository,
  PrismaProductRepository,
  PrismaProductVariantRepository,
  PrismaUserRepository,
  PrismaPointTransactionRepository,
  PrismaPointRewardRepository,
  PrismaFaqRepository,
  PrismaPaymentMethodConfigRepository,
} from '../infrastructure/repositories';
import {
  GetActivityLogsUseCase,
  GetAdminDashboardUseCase,
  CancelOrderUseCase,
  CreateCategoryUseCase,
  CreateCouponUseCase,
  CreateProductUseCase,
  CreateProductVariantUseCase,
  DeactivateProductUseCase,
  DeactivateUserUseCase,
  DeleteCategoryUseCase,
  DeleteCouponUseCase,
  DeliverOrderUseCase,
  GetCategoryDetailUseCase,
  GetCouponDetailUseCase,
  GetOrderDetailUseCase,
  GetProductDetailUseCase,
  GetProductVariantsUseCase,
  GetUserDetailUseCase,
  GetUserOrdersUseCase,
  ListCategoriesUseCase,
  ListCouponsUseCase,
  ListOrdersUseCase,
  ListProductsUseCase,
  ListUsersUseCase,
  LoginUseCase,
  PlaceOrderUseCase,
  ProcessPaymentWebhookUseCase,
  GetPaymentMethodsUseCase,
  RedeemCouponUseCase,
  RefreshTokenUseCase,
  RegisterUserUseCase,
  RefundOrderUseCase,
  StartOrderProcessingUseCase,
  TokenService,
  UpdateCategoryUseCase,
  UpdateCouponUseCase,
  UpdateProductUseCase,
  UpdateUserUseCase,
  ValidateCouponUseCase,
  GetUserPointsUseCase,
  ListAllPointTransactionsUseCase,
  AwardOrderPointsUseCase,
  RevokeOrderPointsUseCase,
  RedeemPointRewardUseCase,
  CreatePointRewardUseCase,
  ListPointRewardsUseCase,
  UpdatePointRewardUseCase,
  DeletePointRewardUseCase,
  CreateFaqUseCase,
  UpdateFaqUseCase,
  DeleteFaqUseCase,
  ListFaqsUseCase,
  GetFaqDetailUseCase,
  GetPaymentMethodConfigsUseCase,
  TogglePaymentMethodConfigUseCase,
} from './use-cases';

const repositoryProviders = [
  { provide: ACTIVITY_LOG_REPOSITORY, useClass: PrismaActivityLogRepository },
  {
    provide: ADMIN_DASHBOARD_REPOSITORY,
    useClass: PrismaAdminDashboardRepository,
  },
  { provide: CATEGORY_REPOSITORY, useClass: PrismaCategoryRepository },
  { provide: USER_REPOSITORY, useClass: PrismaUserRepository },
  { provide: PRODUCT_REPOSITORY, useClass: PrismaProductRepository },
  {
    provide: PRODUCT_VARIANT_REPOSITORY,
    useClass: PrismaProductVariantRepository,
  },
  { provide: COUPON_REPOSITORY, useClass: PrismaCouponRepository },
  { provide: ORDER_REPOSITORY, useClass: PrismaOrderRepository },
  { provide: ORDER_ITEM_REPOSITORY, useClass: PrismaOrderItemRepository },
  {
    provide: POINT_TRANSACTION_REPOSITORY,
    useClass: PrismaPointTransactionRepository,
  },
  {
    provide: POINT_REWARD_REPOSITORY,
    useClass: PrismaPointRewardRepository,
  },
  {
    provide: FAQ_REPOSITORY,
    useClass: PrismaFaqRepository,
  },
  {
    provide: PAYMENT_METHOD_CONFIG_REPOSITORY,
    useClass: PrismaPaymentMethodConfigRepository,
  },
];

const useCaseProviders = [
  TokenService,
  GetActivityLogsUseCase,
  GetAdminDashboardUseCase,
  RegisterUserUseCase,
  LoginUseCase,
  RefreshTokenUseCase,
  CreateCategoryUseCase,
  ListCategoriesUseCase,
  GetCategoryDetailUseCase,
  UpdateCategoryUseCase,
  DeleteCategoryUseCase,
  ListUsersUseCase,
  GetUserDetailUseCase,
  UpdateUserUseCase,
  DeactivateUserUseCase,
  CreateProductUseCase,
  UpdateProductUseCase,
  GetProductDetailUseCase,
  DeactivateProductUseCase,
  CreateProductVariantUseCase,
  GetProductVariantsUseCase,
  ListProductsUseCase,
  CreateCouponUseCase,
  ListCouponsUseCase,
  GetCouponDetailUseCase,
  UpdateCouponUseCase,
  DeleteCouponUseCase,
  ValidateCouponUseCase,
  RedeemCouponUseCase,
  PlaceOrderUseCase,
  ListOrdersUseCase,
  CancelOrderUseCase,
  GetUserOrdersUseCase,
  GetOrderDetailUseCase,
  ProcessPaymentWebhookUseCase,
  GetPaymentMethodsUseCase,
  GetPaymentMethodConfigsUseCase,
  TogglePaymentMethodConfigUseCase,
  StartOrderProcessingUseCase,
  DeliverOrderUseCase,
  RefundOrderUseCase,
  GetUserPointsUseCase,
  ListAllPointTransactionsUseCase,
  AwardOrderPointsUseCase,
  RevokeOrderPointsUseCase,
  RedeemPointRewardUseCase,
  CreatePointRewardUseCase,
  ListPointRewardsUseCase,
  UpdatePointRewardUseCase,
  DeletePointRewardUseCase,
  CreateFaqUseCase,
  UpdateFaqUseCase,
  DeleteFaqUseCase,
  ListFaqsUseCase,
  GetFaqDetailUseCase,
];

@Module({
  imports: [
    forwardRef(() => InfrastructureModule),
    JwtModule.registerAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        secret: configService.getOrThrow<string>('jwt.secret'),
        signOptions: {
          expiresIn: configService.get<string>(
            'jwt.accessExpiration',
            '15m',
          ) as JwtSignOptions['expiresIn'],
        },
      }),
    }),
  ],
  providers: [...repositoryProviders, ...useCaseProviders],
  exports: [JwtModule, ...repositoryProviders, ...useCaseProviders],
})
export class ApplicationModule {}
